/**
 * Companion to session-export.ts: unpack a session-export zip, detect
 * conflicts against the importer's existing data dir, and (on confirm)
 * commit the contents.
 *
 * Two operations exposed:
 *   inspectImport(dir, zipBytes) — extracts to a temp dir, enumerates the
 *     machine / key / session entries, checks for name clashes, returns
 *     a preview + any conflicts. Does NOT write to the data dir.
 *   applyImport(dir, zipBytes)   — same extract, plus (if no conflicts)
 *     copies files into the data dir and returns the session id so the
 *     caller can kick the poller + redirect the UI.
 *
 * Both pipe the bytes through the `unzip` CLI (already a runtime prereq
 * for file-bundle extraction) rather than re-implementing zip reading
 * in pure JS. unzip handles all the decompression and validation we
 * need; we just walk the extracted tree.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
  chmodSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { DataDir, readToml } from "../storage/index.ts";
import { sessionExists } from "./sessions.ts";
import { keyExists } from "./keys.ts";

function machineExists(dir: DataDir, name: string): boolean {
  // domain/machines.ts doesn't export this helper; we keep an inline
  // version rather than bolting another export onto a well-used module.
  try { return existsSync(dir.machineFile(name)); } catch { return false; }
}

export type ImportPreview = {
  session_id: string;
  machine_name: string;
  key_name: string;
  exported_by?: string;
  exported_at?: string;
  botdock_version?: string;
  /** Warnings generated by the probe — e.g. a local_reachable_host substitution
   *  for visibility. Informational, not blocking. */
  notes: string[];
  conflicts: Conflict[];
};

export type Conflict =
  | { kind: "session"; name: string; detail: string }
  | { kind: "machine"; name: string; detail: string }
  | { kind: "key"; name: string; detail: string };

export type ImportApplied = {
  session_id: string;
  machine_name: string;
  key_name: string;
};

export function inspectImport(dir: DataDir, zipBytes: Buffer): ImportPreview {
  return withExtract(zipBytes, (extractDir) => probe(dir, extractDir));
}

export function applyImport(dir: DataDir, zipBytes: Buffer): ImportApplied {
  return withExtract(zipBytes, (extractDir) => {
    const preview = probe(dir, extractDir);
    if (preview.conflicts.length > 0) {
      // This shouldn't normally happen — the UI shows conflicts and hides
      // Import. But enforce again server-side so a bypassed UI can't
      // silently overwrite data.
      const summary = preview.conflicts
        .map((c) => `${c.kind} "${c.name}": ${c.detail}`)
        .join("; ");
      throw new Error(`cannot apply import while conflicts exist — ${summary}`);
    }
    commit(dir, extractDir, preview);
    return {
      session_id: preview.session_id,
      machine_name: preview.machine_name,
      key_name: preview.key_name,
    };
  });
}

// ---- internals ----------------------------------------------------------

type ExtractedLayout = {
  sessionId: string;
  machineName: string;   // from the unpacked machines/<name>.toml
  keyName: string;       // from the unpacked private/keys/<name>/
  metadata: Record<string, unknown> | null;
};

function withExtract<T>(zipBytes: Buffer, fn: (extractDir: string) => T): T {
  const archivePath = join(tmpdir(), `botdock-import-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.zip`);
  const extractDir = mkdtempSync(join(tmpdir(), "botdock-import-extract-"));
  try {
    writeFileSync(archivePath, zipBytes);
    const res = spawnSync("unzip", ["-o", "-q", archivePath, "-d", extractDir], {
      encoding: "utf8",
      timeout: 60_000,
    });
    if (res.status !== 0) {
      const msg = (res.stderr || res.stdout || `unzip exit ${res.status}`).trim();
      throw new Error(`failed to unpack import zip: ${msg}`);
    }
    return fn(extractDir);
  } finally {
    try { rmSync(archivePath, { force: true }); } catch { /* ignore */ }
    try { rmSync(extractDir, { recursive: true, force: true }); } catch { /* ignore */ }
  }
}

function probe(dir: DataDir, extractDir: string): ImportPreview {
  const layout = resolveLayout(extractDir);
  const notes: string[] = [];
  if (layout.metadata?.local_reachable_host) {
    notes.push(
      `Exporter's local machine was rewritten as "${layout.machineName}" `
      + `with host "${layout.metadata.local_reachable_host}".`,
    );
  }

  const conflicts: Conflict[] = [];
  if (sessionExists(dir, layout.sessionId)) {
    conflicts.push({
      kind: "session",
      name: layout.sessionId,
      detail: "a session with this id already exists on your host — delete it or use a different BotDock data dir before importing",
    });
  }
  if (machineExists(dir, layout.machineName)) {
    conflicts.push({
      kind: "machine",
      name: layout.machineName,
      detail: `a machine named "${layout.machineName}" already exists — rename it or delete it first`,
    });
  }
  if (keyExists(dir, layout.keyName)) {
    conflicts.push({
      kind: "key",
      name: layout.keyName,
      detail: `a key nicknamed "${layout.keyName}" already exists — rename it or delete it first`,
    });
  }

  return {
    session_id: layout.sessionId,
    machine_name: layout.machineName,
    key_name: layout.keyName,
    exported_by: layout.metadata?.exported_by as string | undefined,
    exported_at: layout.metadata?.exported_at as string | undefined,
    botdock_version: layout.metadata?.botdock_version as string | undefined,
    notes,
    conflicts,
  };
}

function resolveLayout(extractDir: string): ExtractedLayout {
  const sessionsDir = join(extractDir, "sessions");
  const machinesDir = join(extractDir, "machines");
  const keysDir = join(extractDir, "private", "keys");

  if (!existsSync(sessionsDir)) throw new Error("zip is missing the expected sessions/ dir");
  if (!existsSync(machinesDir)) throw new Error("zip is missing the expected machines/ dir");
  if (!existsSync(keysDir)) throw new Error("zip is missing the expected private/keys/ dir");

  const sessionIds = readdirSync(sessionsDir).filter((n) => {
    const p = join(sessionsDir, n);
    return statSync(p).isDirectory();
  });
  if (sessionIds.length !== 1) {
    throw new Error(`zip should contain exactly one session, found ${sessionIds.length}`);
  }
  const sessionId = sessionIds[0]!;

  const machineTomls = readdirSync(machinesDir).filter((n) => n.endsWith(".toml"));
  if (machineTomls.length !== 1) {
    throw new Error(`zip should contain exactly one machine toml, found ${machineTomls.length}`);
  }
  const machineName = machineTomls[0]!.replace(/\.toml$/, "");

  const keyNames = readdirSync(keysDir).filter((n) => {
    const p = join(keysDir, n);
    return statSync(p).isDirectory();
  });
  if (keyNames.length !== 1) {
    throw new Error(`zip should contain exactly one key dir, found ${keyNames.length}`);
  }
  const keyName = keyNames[0]!;

  const metaPath = join(extractDir, "export_metadata.toml");
  const metadata = existsSync(metaPath) ? readToml<Record<string, unknown>>(metaPath) : null;

  return { sessionId, machineName, keyName, metadata };
}

function commit(dir: DataDir, extractDir: string, layout: ImportPreview): void {
  // Order matters:
  //   1. key (machine references it; if this fails we haven't modified
  //      anything visible to the user yet)
  //   2. machine (session references it)
  //   3. session (last — if this fails, the orphan machine/key is a small
  //      cost but the session won't appear half-registered)
  const keySrc = join(extractDir, "private", "keys", layout.key_name);
  const keyDst = dir.keyDir(layout.key_name);
  mkdirSync(dirname(keyDst), { recursive: true });
  copyTree(keySrc, keyDst, { file: 0o600, other: 0o644, dir: 0o700 });

  const machineSrc = join(extractDir, "machines", `${layout.machine_name}.toml`);
  const machineDst = dir.machineFile(layout.machine_name);
  mkdirSync(dirname(machineDst), { recursive: true });
  copyFileSync(machineSrc, machineDst);
  chmodSync(machineDst, 0o644);

  const sessionSrc = join(extractDir, "sessions", layout.session_id);
  const sessionDst = join(dir.sessionsDir(), layout.session_id);
  mkdirSync(dirname(sessionDst), { recursive: true });
  copyTree(sessionSrc, sessionDst, { file: 0o644, other: 0o644, dir: 0o755 });
}

function copyTree(
  src: string,
  dst: string,
  modes: { file: number; other: number; dir: number },
): void {
  mkdirSync(dst, { recursive: true, mode: modes.dir });
  chmodSync(dst, modes.dir);
  for (const name of readdirSync(src)) {
    const s = join(src, name);
    const d = join(dst, name);
    const st = statSync(s);
    if (st.isDirectory()) {
      copyTree(s, d, modes);
    } else if (st.isFile()) {
      copyFileSync(s, d);
      // Private keys get 600; everything else 644. We detect the key file
      // by its base name rather than by path so the same routine works for
      // session dirs (where nothing is secret).
      const mode = name === "key" ? modes.file : modes.other;
      chmodSync(d, mode);
    }
  }
  // Silence unused-var nag.
  void relative;
}
