/**
 * Best-effort parser for the Claude Code JSONL transcript format.
 *
 * The schema drifts across CC versions; we lean on message.role + content
 * shape rather than the top-level `type` field so we can handle a few
 * variants. Anything we can't classify we keep as `{kind: "unknown"}` with
 * the raw JSON intact so the user can still inspect it.
 */

export type TranscriptContentBlock =
  | { type: "text"; text: string }
  | { type: "tool_use"; id: string; name: string; input: unknown }
  | { type: "tool_result"; tool_use_id: string; content: string; is_error?: boolean }
  | { type: "image" }
  | { type: "other"; raw: unknown };

export type TranscriptTurn = {
  uuid?: string;
  parent_uuid?: string;
  ts?: string;
  kind: "user" | "assistant" | "tool_result" | "system" | "summary" | "unknown";
  blocks: TranscriptContentBlock[];
  raw: Record<string, unknown>;
};

/**
 * Parse the accumulated transcript text (newline-delimited JSON) into turns.
 * Tolerates blank lines and malformed lines (dropped, not fatal).
 */
export function parseTranscript(text: string): TranscriptTurn[] {
  const turns: TranscriptTurn[] = [];
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    let obj: Record<string, unknown>;
    try { obj = JSON.parse(line) as Record<string, unknown>; } catch { continue; }
    turns.push(classify(obj));
  }
  return turns;
}

function classify(obj: Record<string, unknown>): TranscriptTurn {
  const raw = obj;
  const ts = (obj.timestamp as string | undefined) ?? (obj.ts as string | undefined);
  const uuid = (obj.uuid as string | undefined);
  const parent_uuid = (obj.parentUuid as string | undefined) ?? (obj.parent_uuid as string | undefined);

  const topType = (obj.type as string | undefined) ?? "";
  const msg = (obj as any).message as Record<string, unknown> | undefined;
  const role = (msg?.role as string | undefined) ?? "";
  const content = msg?.content;

  // Summary entries (session summary generated by CC on resume) — treat as system.
  if (topType === "summary") {
    return { uuid, parent_uuid, ts, kind: "summary", blocks: [{
      type: "text", text: String((obj as any).summary ?? ""),
    }], raw };
  }

  // Common case: message with role.
  if (role === "user" || role === "assistant") {
    const blocks = Array.isArray(content)
      ? content.map(parseBlock)
      : typeof content === "string"
        ? [{ type: "text", text: content } as TranscriptContentBlock]
        : [{ type: "other", raw: content } as TranscriptContentBlock];
    const isToolResult = role === "user" && blocks.every((b) => b.type === "tool_result");
    return {
      uuid, parent_uuid, ts,
      kind: isToolResult ? "tool_result" : (role as "user" | "assistant"),
      blocks, raw,
    };
  }

  if (topType === "system" || topType === "tool_result") {
    return { uuid, parent_uuid, ts, kind: topType as "system" | "tool_result", blocks: [], raw };
  }

  return { uuid, parent_uuid, ts, kind: "unknown", blocks: [], raw };
}

function parseBlock(block: unknown): TranscriptContentBlock {
  if (!block || typeof block !== "object") return { type: "other", raw: block };
  const b = block as Record<string, unknown>;
  switch (b.type) {
    case "text":
      return { type: "text", text: String(b.text ?? "") };
    case "tool_use":
      return {
        type: "tool_use",
        id: String(b.id ?? ""),
        name: String(b.name ?? ""),
        input: b.input,
      };
    case "tool_result": {
      const c = b.content;
      const text = typeof c === "string"
        ? c
        : Array.isArray(c)
          ? c.map((item: any) => item?.type === "text" ? String(item.text ?? "") : "").join("\n")
          : JSON.stringify(c ?? "");
      return {
        type: "tool_result",
        tool_use_id: String(b.tool_use_id ?? ""),
        content: text,
        is_error: b.is_error === true,
      };
    }
    case "image":
      return { type: "image" };
    default:
      return { type: "other", raw: block };
  }
}
