/**
 * Best-effort parser for agent transcripts. Two flavours supported:
 *
 *   - "cc"    — Claude Code JSONL. Top-level shape varies across CC
 *               versions; we lean on message.role + content shape rather
 *               than the top-level `type` field so we tolerate a few
 *               variants.
 *   - "codex" — OpenAI codex rollout JSONL. Each line is a RolloutLine —
 *               either a session-meta header, a response_item with the
 *               OpenAI-style {role, content} message, an event_msg
 *               lifecycle marker, or a context/compaction record.
 *
 * Anything we can't classify we keep as {kind: "unknown"} with the raw
 * JSON intact so the user can still inspect the line in the panel.
 */

export type TranscriptFormat = "cc" | "codex";

export type TranscriptContentBlock =
  | { type: "text"; text: string }
  | { type: "tool_use"; id: string; name: string; input: unknown }
  | { type: "tool_result"; tool_use_id: string; content: string; is_error?: boolean }
  | { type: "image" }
  | { type: "other"; raw: unknown };

export type TranscriptTurn = {
  uuid?: string;
  parent_uuid?: string;
  ts?: string;
  kind: "user" | "assistant" | "tool_result" | "system" | "summary" | "unknown";
  blocks: TranscriptContentBlock[];
  raw: Record<string, unknown>;
};

/**
 * Parse the accumulated transcript text (newline-delimited JSON) into turns.
 * Tolerates blank lines and malformed lines (dropped, not fatal).
 *
 * `format` defaults to "cc" so existing call sites keep working unchanged;
 * pass "codex" for codex rollout JSONL.
 *
 * Codex's classifier returns null for rows that aren't worth showing
 * (event_msg duplicates of response_item, token_count noise, developer-
 * role envelopes, etc.); those drop here so the panel stays clean.
 */
export function parseTranscript(
  text: string,
  format: TranscriptFormat = "cc",
): TranscriptTurn[] {
  const turns: TranscriptTurn[] = [];
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    let obj: Record<string, unknown>;
    try { obj = JSON.parse(line) as Record<string, unknown>; } catch { continue; }
    const turn = format === "codex" ? classifyCodex(obj) : classify(obj);
    if (turn) turns.push(turn);
  }
  return turns;
}

function classify(obj: Record<string, unknown>): TranscriptTurn {
  const raw = obj;
  const ts = (obj.timestamp as string | undefined) ?? (obj.ts as string | undefined);
  const uuid = (obj.uuid as string | undefined);
  const parent_uuid = (obj.parentUuid as string | undefined) ?? (obj.parent_uuid as string | undefined);

  const topType = (obj.type as string | undefined) ?? "";
  const msg = (obj as any).message as Record<string, unknown> | undefined;
  const role = (msg?.role as string | undefined) ?? "";
  const content = msg?.content;

  // Summary entries (session summary generated by CC on resume).
  if (topType === "summary") {
    const summary = (obj as any).summary;
    const text = typeof summary === "string" && summary.length > 0 ? summary : "";
    return {
      uuid, parent_uuid, ts, kind: "summary",
      blocks: text ? [{ type: "text", text }] : [],
      raw,
    };
  }

  // System entries (session init, compaction notices, etc). Surface whatever
  // text-like fields we can find so the row isn't empty.
  if (topType === "system") {
    const subtype = (obj as any).subtype as string | undefined;
    const text  = (obj as any).text  as string | undefined;
    const toolUseResult = (obj as any).toolUseResult;
    const parts: TranscriptContentBlock[] = [];
    if (subtype) parts.push({ type: "text", text: `[${subtype}]` });
    if (text)    parts.push({ type: "text", text });
    if (typeof toolUseResult === "string" && toolUseResult) parts.push({ type: "text", text: toolUseResult });
    return { uuid, parent_uuid, ts, kind: "system", blocks: parts, raw };
  }

  // Standard case: message with a role.
  if (role === "user" || role === "assistant") {
    const blocks = Array.isArray(content)
      ? content.map(parseBlock).filter((b) =>
          !(b.type === "text" && !b.text.trim()),  // drop empty-text noise
        )
      : typeof content === "string" && content.trim()
        ? [{ type: "text", text: content } as TranscriptContentBlock]
        : content !== undefined
          ? [{ type: "other", raw: content } as TranscriptContentBlock]
          : [];
    const isToolResult = role === "user" && blocks.length > 0 && blocks.every((b) => b.type === "tool_result");
    return {
      uuid, parent_uuid, ts,
      kind: isToolResult ? "tool_result" : (role as "user" | "assistant"),
      blocks, raw,
    };
  }

  if (topType === "tool_result") {
    return { uuid, parent_uuid, ts, kind: "tool_result", blocks: [], raw };
  }

  return { uuid, parent_uuid, ts, kind: "unknown", blocks: [], raw };
}

/**
 * Codex rollout classification.
 *
 * Wire format observed in real rollouts (codex CLI 0.125.0):
 *   { timestamp, type: "<envelope>", payload: { type: "<subtype>", ... } }
 *
 * Envelope variants and how we render each:
 *   - "session_meta"    — first line. Carries session id + cwd + a giant
 *                          base_instructions blob. We render a one-line
 *                          "[session opened …]" breadcrumb and DROP the
 *                          base_instructions (the user doesn't need to
 *                          read codex's system prompt every session).
 *   - "response_item"   — payload.type === "message" with role + content.
 *                          Real conversation lives here; user / assistant
 *                          turns get rendered, developer (system prompt
 *                          envelope) gets dropped, and user-role rows
 *                          whose only content looks like a `<tagged>`
 *                          machine envelope (environment_context,
 *                          permissions instructions, …) get dropped too.
 *   - "event_msg"       — payload.type names the lifecycle event:
 *                          - user_message / agent_message duplicate the
 *                            response_item rows above; we drop them.
 *                          - token_count is periodic noise; drop.
 *                          - *_delta is streaming-fragment noise; drop.
 *                          - task_started / task_complete / task_aborted
 *                            / turn_aborted / error stay as compact
 *                            breadcrumbs.
 *                          - any other event keeps a labelled breadcrumb
 *                            so unknown variants stay visible.
 *   - "turn_context"    — per-turn config snapshot. Internal only; drop.
 *   - any other         — pass through as "unknown" for the raw inspector.
 *
 * Returning null from this function makes parseTranscript skip the row,
 * which is how dropped variants disappear from the panel.
 */
function classifyCodex(obj: Record<string, unknown>): TranscriptTurn | null {
  const raw = obj;
  const ts = (obj.timestamp as string | undefined) ?? (obj.ts as string | undefined);
  const topType = String(obj.type ?? "");
  const payload = (obj.payload as Record<string, unknown> | undefined) ?? {};

  if (topType === "session_meta") {
    const sid = String(payload.id ?? "");
    const cwd = String(payload.cwd ?? "");
    const shortSid = sid ? sid.slice(0, 8) : "";
    const text = `[session opened${shortSid ? ` ${shortSid}` : ""}${cwd ? ` · cwd ${cwd}` : ""}]`;
    return {
      ts, kind: "system",
      blocks: [{ type: "text", text }],
      raw,
    };
  }

  if (topType === "turn_context") return null;

  if (topType === "event_msg") {
    const subType = String(payload.type ?? "");
    // Duplicates of response_item — we render the response_item version,
    // not these.
    if (subType === "user_message" || subType === "agent_message") return null;
    // Periodic noise — token_count fires every couple of seconds.
    if (subType === "token_count") return null;
    // Streaming deltas — fragment-level events, useful for activity
    // detection on the server but useless as user-facing rows.
    if (/_delta$/.test(subType)) return null;
    // Other event_msg variants keep a small labelled breadcrumb so the
    // user can see lifecycle markers (task_started / task_complete /
    // turn_aborted / error / etc.) without drowning in noise. Use a
    // human-friendly version of the snake_case label.
    const label = subType ? subType.replace(/_/g, " ") : "event";
    return {
      ts, kind: "system",
      blocks: [{ type: "text", text: `[${label}]` }],
      raw,
    };
  }

  if (topType === "response_item") {
    const itemType = String(payload.type ?? "");
    // We only render `message`-shaped response items for now. tool_call /
    // function_call etc. fall through to "unknown" so they're inspectable
    // via the raw view without polluting the readable panel.
    if (itemType !== "message") return null;
    const role = String(payload.role ?? "");
    // Developer role is codex's system-prompt envelope — internal,
    // never of interest to the operator looking at the conversation.
    if (role === "developer") return null;

    const content = payload.content;
    const blocks: TranscriptContentBlock[] = [];
    if (Array.isArray(content)) {
      for (const c of content) blocks.push(parseCodexBlock(c));
    } else if (typeof content === "string") {
      blocks.push({ type: "text", text: content });
    }
    const cleaned = blocks.filter((b) => !(b.type === "text" && !b.text.trim()));
    if (cleaned.length === 0) return null;

    // Drop auto-generated user envelopes — codex prepends user-role
    // messages whose entire content is a single `<environment_context>`,
    // `<permissions instructions>`, `<collaboration_mode>`, etc. block.
    // The user never typed those; they're scaffolding.
    if (role === "user") {
      const allEnvelope = cleaned.every((b) =>
        b.type === "text" && /^\s*<[a-z_][a-z0-9_]*>/i.test(b.text)
      );
      if (allEnvelope) return null;
    }

    const kind = role === "assistant" ? "assistant"
      : role === "user" ? "user"
      : "system";
    return { ts, kind, blocks: cleaned, raw };
  }

  return { ts, kind: "unknown", blocks: [], raw };
}

/** Codex content blocks come as `{type: "input_text" | "output_text", text}`
 *  rather than CC's plain `{type: "text", text}`. Anything else (images,
 *  tool calls, etc.) passes through as raw for the inspector view. */
function parseCodexBlock(block: unknown): TranscriptContentBlock {
  if (!block || typeof block !== "object") return { type: "other", raw: block };
  const b = block as Record<string, unknown>;
  const t = String(b.type ?? "");
  if (t === "input_text" || t === "output_text" || t === "text") {
    return { type: "text", text: String(b.text ?? "") };
  }
  return { type: "other", raw: block };
}

function parseBlock(block: unknown): TranscriptContentBlock {
  if (!block || typeof block !== "object") return { type: "other", raw: block };
  const b = block as Record<string, unknown>;
  switch (b.type) {
    case "text":
      return { type: "text", text: String(b.text ?? "") };
    case "tool_use":
      return {
        type: "tool_use",
        id: String(b.id ?? ""),
        name: String(b.name ?? ""),
        input: b.input,
      };
    case "tool_result": {
      const c = b.content;
      const text = typeof c === "string"
        ? c
        : Array.isArray(c)
          ? c.map((item: any) => item?.type === "text" ? String(item.text ?? "") : "").join("\n")
          : JSON.stringify(c ?? "");
      return {
        type: "tool_result",
        tool_use_id: String(b.tool_use_id ?? ""),
        content: text,
        is_error: b.is_error === true,
      };
    }
    case "image":
      return { type: "image" };
    default:
      return { type: "other", raw: block };
  }
}
