#!/usr/bin/env bun
/**
 * Walk web/dist/ and emit src/server/embedded.ts with the frontend bundle
 * serialized as base64 keyed by URL path. Invoked by scripts/build.sh just
 * before `bun build --compile`.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative, extname, resolve } from "node:path";

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js":   "application/javascript; charset=utf-8",
  ".css":  "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg":  "image/svg+xml",
  ".ico":  "image/x-icon",
  ".woff":  "font/woff",
  ".woff2": "font/woff2",
  ".png":  "image/png",
  ".jpg":  "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif":  "image/gif",
  ".map":  "application/json",
};

const root = resolve(import.meta.dir, "..");
const dist = join(root, "web", "dist");
const out = join(root, "src", "server", "embedded.ts");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

function main() {
  let files: string[];
  try {
    files = walk(dist);
  } catch (e) {
    console.error(`web/dist/ not found. Run \`bun run web:build\` first.`);
    process.exit(1);
  }

  const entries: string[] = [];
  let total = 0;
  for (const abs of files) {
    const rel = "/" + relative(dist, abs).split(/[\\/]/).join("/");
    const data = readFileSync(abs);
    total += data.length;
    const mime = MIME[extname(abs)] ?? "application/octet-stream";
    entries.push(
      `  ${JSON.stringify(rel)}: { mime: ${JSON.stringify(mime)}, data: _b64(${JSON.stringify(data.toString("base64"))}) },`,
    );
  }

  const src = [
    `// AUTO-GENERATED by scripts/embed-dist.ts — do not edit by hand.`,
    `// Populated at build time with ${files.length} files (${total} bytes).`,
    `export type EmbeddedFile = { mime: string; data: Uint8Array };`,
    `const _b64 = (s: string) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));`,
    `export const embeddedFiles: Record<string, EmbeddedFile> = {`,
    ...entries,
    `};`,
    ``,
  ].join("\n");

  writeFileSync(out, src);
  console.log(`embedded ${files.length} files (${total} bytes) → ${relative(root, out)}`);
}

main();
